import { translator } from '@globalHelpers/translations'

export const avatarOptions = [
  { key: 'topType', value: translator('topType') },
  { key: 'accessoriesType', value: translator('accessoriesType') },
  { key: 'hatColor', value: translator('hatColor') },
  { key: 'hairColor', value: translator('hairColor') },
  { key: 'facialHairType', value: translator('facialHairType') },
  { key: 'facialHairColor', value: translator('facialHairColor') },
  { key: 'clotheType', value: translator('clotheType') },
  { key: 'clotheColor', value: translator('clotheColor') },
  { key: 'graphicType', value: translator('graphicType') },
  { key: 'eyeType', value: translator('eyeType') },
  { key: 'eyebrowType', value: translator('eyebrowType') },
  { key: 'mouthType', value: translator('mouthType') },
  { key: 'skinColor', value: translator('skinColor') },
]

export const getOptions = (name) => {
  const options = {
    topType: [
      { key: 'NoHair', value: translator('NoHair') },
      { key: 'Eyepatch', value: translator('Eyepatch') },
      { key: 'Hat', value: translator('Hat') },
      { key: 'Hijab', value: translator('Hijab') },
      { key: 'Turban', value: translator('Turban') },
      { key: 'WinterHat1', value: translator('WinterHat1') },
      { key: 'WinterHat2', value: translator('WinterHat2') },
      { key: 'WinterHat3', value: translator('WinterHat3') },
      { key: 'WinterHat4', value: translator('WinterHat4') },
      { key: 'LongHairBigHair', value: translator('LongHairBigHair') },
      { key: 'LongHairBob', value: translator('LongHairBob') },
      { key: 'LongHairBun', value: translator('LongHairBun') },
      { key: 'LongHairCurly', value: translator('LongHairCurly') },
      { key: 'LongHairCurvy', value: translator('LongHairCurvy') },
      { key: 'LongHairDreads', value: translator('LongHairDreads') },
      { key: 'LongHairFrida', value: translator('LongHairFrida') },
      { key: 'LongHairFro', value: translator('LongHairFro') },
      { key: 'LongHairFroBand', value: translator('LongHairFroBand') },
      { key: 'LongHairNotTooLong', value: translator('LongHairNotTooLong') },
      { key: 'LongHairShavedSides', value: translator('LongHairShavedSides') },
      { key: 'LongHairMiaWallace', value: translator('LongHairMiaWallace') },
      { key: 'LongHairStraight', value: translator('LongHairStraight') },
      { key: 'LongHairStraight2', value: translator('LongHairStraight2') },
      { key: 'LongHairStraightStrand', value: translator('LongHairStraightStrand') },
      { key: 'ShortHairDreads01', value: translator('ShortHairDreads01') },
      { key: 'ShortHairDreads02', value: translator('ShortHairDreads02') },
      { key: 'ShortHairFrizzle', value: translator('ShortHairFrizzle') },
      { key: 'ShortHairShaggyMullet', value: translator('ShortHairShaggyMullet') },
      { key: 'ShortHairShortCurly', value: translator('ShortHairShortCurly') },
      { key: 'ShortHairShortFlat', value: translator('ShortHairShortFlat') },
      { key: 'ShortHairShortRound', value: translator('ShortHairShortRound') },
      { key: 'ShortHairShortWaved', value: translator('ShortHairShortWaved') },
      { key: 'ShortHairSides', value: translator('ShortHairSides') },
      { key: 'ShortHairTheCaesar', value: translator('ShortHairTheCaesar') },
      { key: 'ShortHairTheCaesarSidePart', value: translator('ShortHairTheCaesarSidePart') },
    ],
    accessoriesType: [
      { key: 'Blank', value: translator('Blank') },
      { key: 'Kurt', value: translator('Kurt') },
      { key: 'Prescription01', value: translator('Prescription01') },
      { key: 'Prescription02', value: translator('Prescription02') },
      { key: 'Round', value: translator('Round') },
      { key: 'Sunglasses', value: translator('Sunglasses') },
      { key: 'Wayfarers', value: translator('Wayfarers') },
    ],
    hatColor: [
      { key: 'Black', value: translator('Black') },
      { key: 'Blue01', value: translator('Blue01') },
      { key: 'Blue02', value: translator('Blue02') },
      { key: 'Blue03', value: translator('Blue03') },
      { key: 'Gray01', value: translator('Gray01') },
      { key: 'Gray02', value: translator('Gray02') },
      { key: 'Heather', value: translator('Heather') },
      { key: 'PastelBlue', value: translator('PastelBlue') },
      { key: 'PastelGreen', value: translator('PastelGreen') },
      { key: 'PastelRed', value: translator('PastelRed') },
      { key: 'PastelYellow', value: translator('PastelYellow') },
      { key: 'Pink', value: translator('Pink') },
      { key: 'Red', value: translator('Red') },
      { key: 'White', value: translator('White') },
    ],
    hairColor: [
      { key: 'Auburn', value: translator('Auburn') },
      { key: 'Black', value: translator('Black') },
      { key: 'Blonde', value: translator('Blonde') },
      { key: 'BlondeGolden', value: translator('BlondeGolden') },
      { key: 'Brown', value: translator('Brown') },
      { key: 'BrownDark', value: translator('BrownDark') },
      { key: 'PastelPink', value: translator('PastelPink') },
      { key: 'Platinum', value: translator('Platinum') },
      { key: 'Red', value: translator('Red') },
      { key: 'SilverGray', value: translator('SilverGray') },
    ],
    facialHairType: [
      { key: 'Blank', value: translator('Blank') },
      { key: 'BeardMedium', value: translator('BeardMedium') },
      { key: 'BeardLight', value: translator('BeardLight') },
      { key: 'BeardMajestic', value: translator('BeardMajestic') },
      { key: 'MoustacheFancy', value: translator('MoustacheFancy') },
      { key: 'MoustacheMagnum', value: translator('MoustacheMagnum') },
    ],
    facialHairColor: [
      { key: 'Auburn', value: translator('Auburn') },
      { key: 'Black', value: translator('Black') },
      { key: 'Blonde', value: translator('Blonde') },
      { key: 'BlondeGolden', value: translator('BlondeGolden') },
      { key: 'Brown', value: translator('Brown') },
      { key: 'BrownDark', value: translator('BrownDark') },
      { key: 'Platinum', value: translator('Platinum') },
      { key: 'Red', value: translator('Red') },
    ],
    clotheType: [
      { key: 'BlazerShirt', value: translator('BlazerShirt') },
      { key: 'BlazerSweater', value: translator('BlazerSweater') },
      { key: 'CollarSweater', value: translator('CollarSweater') },
      { key: 'GraphicShirt', value: translator('GraphicShirt') },
      { key: 'Hoodie', value: translator('Hoodie') },
      { key: 'Overall', value: translator('Overall') },
      { key: 'ShirtCrewNeck', value: translator('ShirtCrewNeck') },
      { key: 'ShirtScoopNeck', value: translator('ShirtScoopNeck') },
      { key: 'ShirtVNeck', value: translator('ShirtVNeck') },
    ],
    clotheColor: [
      { key: 'Black', value: translator('Black') },
      { key: 'Blue01', value: translator('Blue01') },
      { key: 'Blue02', value: translator('Blue02') },
      { key: 'Blue03', value: translator('Blue03') },
      { key: 'Gray01', value: translator('Gray01') },
      { key: 'Gray02', value: translator('Gray02') },
      { key: 'Heather', value: translator('Heather') },
      { key: 'PastelBlue', value: translator('PastelBlue') },
      { key: 'PastelGreen', value: translator('PastelGreen') },
      { key: 'PastelOrange', value: translator('PastelOrange') },
      { key: 'PastelRed', value: translator('PastelRed') },
      { key: 'PastelYellow', value: translator('PastelYellow') },
      { key: 'Pink', value: translator('Pink') },
      { key: 'Red', value: translator('Red') },
      { key: 'White', value: translator('White') },
    ],
    graphicType: [
      { key: 'Bat', value: translator('Bat') },
      { key: 'Cumbia', value: translator('Cumbia') },
      { key: 'Deer', value: translator('Deer') },
      { key: 'Diamond', value: translator('Diamond') },
      { key: 'Hola', value: translator('Hola') },
      { key: 'Pizza', value: translator('Pizza') },
      { key: 'Resist', value: translator('Resist') },
      { key: 'Selena', value: translator('Selena') },
      { key: 'Bear', value: translator('Bear') },
      { key: 'SkullOutline', value: translator('SkullOutline') },
      { key: 'Skull', value: translator('Skull') },
    ],
    eyeType: [
      { key: 'Close', value: translator('Close') },
      { key: 'Cry', value: translator('Cry') },
      { key: 'Default', value: translator('Default') },
      { key: 'Dizzy', value: translator('Dizzy') },
      { key: 'EyeRoll', value: translator('EyeRoll') },
      { key: 'Happy', value: translator('Happy') },
      { key: 'Hearts', value: translator('Hearts') },
      { key: 'Side', value: translator('Side') },
      { key: 'Squint', value: translator('Squint') },
      { key: 'Surprised', value: translator('Surprised') },
      { key: 'Wink', value: translator('Wink') },
      { key: 'WinkWacky', value: translator('WinkWacky') },
    ],
    eyebrowType: [
      { key: 'Angry', value: translator('Angry') },
      { key: 'AngryNatural', value: translator('AngryNatural') },
      { key: 'Default', value: translator('Default') },
      { key: 'DefaultNatural', value: translator('DefaultNatural') },
      { key: 'FlatNatural', value: translator('FlatNatural') },
      { key: 'RaisedExcited', value: translator('RaisedExcited') },
      { key: 'RaisedExcitedNatural', value: translator('RaisedExcitedNatural') },
      { key: 'SadConcerned', value: translator('SadConcerned') },
      { key: 'SadConcernedNatural', value: translator('SadConcernedNatural') },
      { key: 'UnibrowNatural', value: translator('UnibrowNatural') },
      { key: 'UpDown', value: translator('UpDown') },
      { key: 'UpDownNatural', value: translator('UpDownNatural') },
    ],
    mouthType: [
      { key: 'Concerned', value: translator('Concerned') },
      { key: 'Default', value: translator('Default') },
      { key: 'Disbelief', value: translator('Disbelief') },
      { key: 'Eating', value: translator('Eating') },
      { key: 'Grimace', value: translator('Grimace') },
      { key: 'Sad', value: translator('Sad') },
      { key: 'ScreamOpen', value: translator('ScreamOpen') },
      { key: 'Serious', value: translator('Serious') },
      { key: 'Smile', value: translator('Smile') },
      { key: 'Tongue', value: translator('Tongue') },
      { key: 'Twinkle', value: translator('Twinkle') },
      { key: 'Vomit', value: translator('Vomit') },
    ],
    skinColor: [
      { key: 'Tanned', value: translator('Tanned') },
      { key: 'Yellow', value: translator('Yellow') },
      { key: 'Pale', value: translator('Pale') },
      { key: 'Light', value: translator('Light') },
      { key: 'Brown', value: translator('Brown') },
      { key: 'DarkBrown', value: translator('DarkBrown') },
      { key: 'Black', value: translator('Black') },
    ],
  }

  return options[name] || []
}

const getRandomOption = (name) => {
  const options = getOptions(name)
  const randomIndex = Math.floor(Math.random() * options.length)
  return options[randomIndex].key
}

export const getRandomAvatarOptions = () => {
  return {
    topType: getRandomOption('topType'),
    accessoriesType: getRandomOption('accessoriesType'),
    hairColor: getRandomOption('hairColor'),
    hatColor: getRandomOption('hatColor'),
    facialHairType: getRandomOption('facialHairType'),
    facialHairColor: getRandomOption('facialHairColor'),
    clotheType: getRandomOption('clotheType'),
    clotheColor: getRandomOption('clotheColor'),
    eyeType: getRandomOption('eyeType'),
    eyebrowType: getRandomOption('eyebrowType'),
    mouthType: getRandomOption('mouthType'),
    skinColor: getRandomOption('skinColor'),
    graphicType: getRandomOption('graphicType'),
  }
}

export const defaultAvatarState = {
  topType: '',
  accessoriesType: '',
  hairColor: '',
  hatColor: '',
  facialHairType: '',
  facialHairColor: '',
  clotheType: '',
  clotheColor: '',
  eyeType: '',
  eyebrowType: '',
  mouthType: '',
  skinColor: '',
  graphicType: '',
}
